### ISSUE TITLE
Players: Checking…

### ISSUE THREAD

**Issue by cronner** [Alanaktion/MCHostPanel#15]
It just keeps saying Players: Checking…nothing happens
Using Nginx with php5-fpm

**Comment by Alanaktion** [comment]
Make sure you have `enable-query` set to `true` in your `server.properties` file. I've made this the default for new servers now.

**Comment by pchard** [comment]
This isn't working for me, even though I have enable-query=true ..

**Comment by Alanaktion** [comment]
@pchard You may want to check that you have the `query_port` setting the same as the `server_port` in `server.properties` as well. I'm not sure what else would prevent this from working, but if that's not it I can probably look at it some more.
