### ISSUE TITLE
The webpage has a redirect loop

### ISSUE THREAD

**Issue by WebDevelopNYC** [Alanaktion/MCHostPanel#16]
This webpage has a redirect loop

ERR_TOO_MANY_REDIRECTS

**Comment by Alanaktion** [comment]
Which page? I haven't had this happen to me.

**Comment by xCoderTV** [comment]
I have this problem aswell.

**Comment by Alanaktion** [comment]
@xCoderTV that sounds like a permissions problem. Are you sure the `data` folder has write access for the web server user?

**Comment by SkidMaster** [comment]
Can confirm that this bug is fixed after giving ownership to apache. Nothing to worry about with proper config, but should include in documentation.

**Comment by Alanaktion** [comment]
I've added a note in the readme.
