### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by XxSkydevil06xX** [Alanaktion/MCHostPanel#17]
It Says Undefined index: error in C:\wamp\www\Server Control Panel\index.php on line 44 And Says Undefined index: user in C:\wamp\www\Server Control Panel\index.php on line 15 And When I Login It Says Warning: require_once(data/config.php): failed to open stre am: No such file or directory in C:\wamp\www\Server Control Panel\inc\lib.php on line 3 And Says require_once(): Failed opening required 'data/config.php' (include_path='.;C:\php\pear') in C:\wamp\www\Server Control Panel\inc\lib.php on line 3 You Better Fix This

**Comment by Alanaktion** [comment]
Commit 9b15d75 should fix the first undefined index error, along with some others, but to fix the `config.php` errors, you need to follow the installation instructions. Copy `data/config-sample.php` to `config.php` and edit it with your config values.
