### ISSUE TITLE
Start Button

### ISSUE THREAD

**Issue by XxSkydevil06xX** [Alanaktion/MCHostPanel#20]
When I Press Start Server It Does Not Start And Players Says Unkown Running On X10hosting Linux VPS

**Comment by SkidMaster** [comment]
Note that GNU Screen must be installed. Not an issue if configured correctly, but should be noted in documentation.

**Comment by Alanaktion** [comment]
Ensure your web server has permissions to access both the MCHostPanel directory and the Minecraft server's directory, that GNU Screen and Java are installed, and that you have enough memory to start the server (it should run on 384MB or so, but I'd highly recommend at least 2 GB).
