### ISSUE TITLE
once installed the panel wont remember password.

### ISSUE THREAD

**Issue by th2000125** [Alanaktion/MCHostPanel#24]
once I install using install.php the panel first of all does this.
"This web page has a redirect loop
ERR_TOO_MANY_REDIRECTS" - Google Chrome
then on Firefox the page shows but the password is apparently incorrect.

Thanks for your time, great project!

**Comment by th2000125** [comment]
Ok I reinstalled and am having the same issue after needing to re-login.
and I have noticed the server wont start either, well it will on one server but not on the other.

**Comment by Alanaktion** [comment]
This should be fixed in 603d3794066658a35fabd6e511eeeeaa0539804c.
