### ISSUE TITLE
The page isn't redirecting properly

### ISSUE THREAD

**Issue by Nicocraft71** [Alanaktion/MCHostPanel#27]
Hello, I have Nginx and i have this error on dashboard.php : 
"The page isn't redirecting properly"

I have the same probleme with apache2 ! Help me please :(

**Comment by Nicocraft71** [comment]
Ok, i do : "Ensure the web server user has write access to the main MCHP and data/ directories."

and i REBOOT my vps

**Comment by Alanaktion** [comment]
This should be fixed in 603d3794066658a35fabd6e511eeeeaa0539804c.
