### ISSUE TITLE
Servers will not start

### ISSUE THREAD

**Issue by DarkN3ss61** [Alanaktion/MCHostPanel#30]
i have installed this on a windows server 2012 r2 machine running iis.it looks as if it has installed correctly as the website works fine and I can create other users, but when I try to start a spogit server nothing happens,I click the button it disables for a second and then reenables.

Can you please fix s or tel me how I can fix it, thanks

**Comment by Alanaktion** [comment]
This won't work on Windows Server. It requires GNU Screen and uses several command line features only available on a Linux/UNIX platform.
