### ISSUE TITLE
Problem with the installation

### ISSUE THREAD

**Issue by balas16k** [Alanaktion/MCHostPanel#32]
We follow the installation to the part to create a user in /install.php, but we can not access with the user

**Comment by Alanaktion** [comment]
Make sure the server had write permissions for the `data/users/` directory, otherwise it can't save the new user properly.

**Comment by balas16k** [comment]
thanks

**Comment by Alanaktion** [comment]
@balas16k You can fork the code and make whatever modifications you'd like, then use pull requests to add your new features to the main repo.
