### ISSUE TITLE
servers not starting

### ISSUE THREAD

**Issue by kevinboeger** [Alanaktion/MCHostPanel#37]
when i want start the server it will go online and in a fews seconds offline again pls help :(

**Comment by cthulhuely** [comment]
I could come from your Minecraft server configuration, do you have any error log ?

**Comment by Alanaktion** [comment]
My guess is that you're running a recent Minecraft server and haven't set `eula=true` in the eula.txt file. Minecraft 1.7 and higher require that before starting the server. The console on the Dashboard or Console tab should have information about why the server isn't starting.

If nothing is being logged and your eula.txt is fine, make sure you have the right permissions on the files. They should be owned by and writable by the user running the control panel (likely www-data).
