### ISSUE TITLE
[Enhancement] Add php7.0 compatability

### ISSUE THREAD

**Issue by Dooleylabs** [Alanaktion/MCHostPanel#39]
It's impossible to start | stop | restart a server with php7.0. Everything works perfectly with php5.

**Comment by Alanaktion** [comment]
It's working fine for me on PHP 7.0.7 on Arch Linux as long as a compatible `java` and `screen` are installed. Are you getting any specific error messages in your PHP log?

**Comment by Dooleylabs** [comment]
I'm not getting any errors. I'm using Debian 8 sid. After removing php 7, it works as it did before. Not sure where the issue lies.

**Comment by Alanaktion** [comment]
I can't reproduce this with the latest sid either. Starting and stopping servers as well as sending commands works as expected on PHP 7.0 with Apache.

From a fresh sid install, as root:

```
apt-get install php7.0 apache2 screen openjdk-8-jre-headless git
a2enmod php7.0
a2dismod mpm_event
a2enmod mpm_prefork
service apache2 restart
cd /var/www/html
rm index.html
git clone https://github.com/Alanaktion/MCHostPanel.git .
cp data/config-sample.php data/config.php
chown -R www-data: .
```

Does everything on the panel work except starting/stopping (e.g. file uploads, admin panel)? It seems like it could potentially be a setup problem, like if `shell_exec()` is disabled in `php.ini` or the web server user doesn't have permission to run the server.

**Comment by Dooleylabs** [comment]
You know, I think you may be onto something... I'll test it and report back as soon as I've time.

**Comment by Dooleylabs** [comment]
The issue was in /etc/php/7.0/apache2/php.ini on a line called disable_functions.
There was something along the lines of pncl_exec in it, which disabled shell_exec() by default on PHP 7.0 in Debian 8 (SID). Thanks for your help!
