### ISSUE TITLE
Installation not working

### ISSUE THREAD

**Issue by XenoGaming** [Alanaktion/MCHostPanel#41]
So I uploaded all the files in the ZIP to /var/www/html/ in my Debian 8 VPS but when I try to access the web page it just comes up blank. I have php5, apache2, MySQL, and phpmyadmin installed. What did I do wrong?

**Comment by Alanaktion** [comment]
Check `/var/log/apache2/error.log` for details on what's not working. Also MySQL and PHPMyAdmin are not currently required for MCHostPanel, it stores user data in JSON files.

Most likely you'll have permissions issues on the `/var/www/html/` folder contents, you should be able to work around that by running `sudo chown -R www-data: /var/www/html`.
