### ISSUE TITLE
Screen directory permissions problem

### ISSUE THREAD

**Issue by Tiara2000** [Alanaktion/MCHostPanel#49]
Hello! I have an issue when i am going to set things up with the "screen".
Firstly, apache couldnt create a folder in the directory: /var/run/screen/

So i created one manually and gave apache the ownership of it. Now i get the error: 
Directory /var/run/screen/S-apache must have mode 700.

So i set the S-apache folder permissions to 700 and i get a new error:
Cannot opendir /var/run/screen/S-apache: Permission denied

I have no idea how to fix this so if you know the solution, Please help me:)

Ps: This panel looks amazing

My server machine info:
OS: Cent OS 7
PHP Version: 5.6.31
Screen Version: 4.01.00devel (GNU)

Thanks!

**Comment by Alanaktion** [comment]
S-apache probably needs to be owned by the apache user too, if it isn't already. Some issues with screen's permissions are fixed by a reboot, so that may work too.

**Comment by Tiara2000** [comment]
I tried and it didnt work, The folder "S-apache" i created manually got deleted when i rebooted tho,
Is there a command to create a screen folder for apache? if so whats that command then?

**Comment by Alanaktion** [comment]
Under normal circumstances this should work just fine, but it's possible you have something weird going on with your permissions somewhere higher up. Manually resetting everything there might work, but other than that there's not much I'm aware of to fix something like this.

As root:
```bash
chmod 775 /var/run/screen
mkdir -p /var/run/screen/S-apache
chown apache: /var/run/screen/S-apache
chmod -R 700 /var/run/screen/S-apache
```

The `/var` and `/var/run` directories should generally also have `755` permissions.

**Comment by Tiara2000** [comment]
I will try, Thank you for all the help
