### ISSUE TITLE
Can I have Better Instructions on how to Install this on a Debian GNU/Linux 9 os please and thank you.

### ISSUE THREAD

**Issue by Redthered** [Alanaktion/MCHostPanel#53]
Can I have Better Instructions on how to Install this on a Debian GNU/Linux 9 os please and thank you.

**Comment by gamersalpha** [comment]
Hello 

i m stuck

First i do that : 

http://192.168.50.12/MCHostPanel/install.php

but when i try to log, 
i can log, and no message is show ; 

i can pass this : 

![image](https://user-images.githubusercontent.com/32466950/38469794-9e109aaa-3b5a-11e8-9b6d-32a961fecc0f.png)

what is wrong please : 

how debug please

**Comment by gamersalpha** [comment]
i found solution here 👍 
https://github.com/Alanaktion/MCHostPanel/issues/41


works for me 
thanks
